# Ch2. Vector Spaces and Norms

## 2.1 Vector Spaces

In [20]:
# Import library
import numpy as np

In [21]:
# Subspace & linear combination
v1 = np.array([1, 0])
v2 = np.array([0, 1])
a, b = 2, -3
lin_comb = a*v1 + b*v2  
print("Linear combination:", lin_comb)  

Linear combination: [ 2 -3]


## 2.2 Inner products and Norms

### 2.2.1 Inner products

In [22]:
# Inner product & orthogonalitty
x = np.array([1, 2, 3])
y = np.array([-3, 0, 1])
dot = np.dot(x, y)
print("Inner product:", dot)
print("Orthogonal?", np.isclose(dot, 0))

Inner product: 0
Orthogonal? True


In [23]:
# Caushy-Schwarz inequality
lhs = abs(np.dot(x, y))
rhs = np.linalg.norm(x) * np.linalg.norm(y)
print("Cauchy-Schwarz holds?", lhs <= rhs)

Cauchy-Schwarz holds? True


### 2.2.2 Norms

In [24]:
# Vector norms
z = np.array([3, -4])
print("L1 norm:", np.linalg.norm(z, 1))  
print("Euclidean norm:", np.linalg.norm(z, 2)) 
print("Max norm:", np.linalg.norm(z, np.inf))

L1 norm: 7.0
Euclidean norm: 5.0
Max norm: 4.0


In [25]:
# Matrix norms
A = np.array([[1, -2],
              [3,  4]])

fro = np.linalg.norm(A, 'fro')     # Frobenius norm
spec = np.linalg.norm(A, 2)        # Spectral norm 

print("Frobenius norm:", round(fro, 2))
print("Spectral norm:", round(spec, 2))

Frobenius norm: 5.48
Spectral norm: 5.12


## 2.3 Fundamenetal Theorem of Linear Algebra

### 2.3.1 Fundamental Theorem of Linear Algebra

In [26]:
# Import library
import numpy as np
from scipy.linalg import null_space
from numpy.linalg import matrix_rank

In [27]:
# Create matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Column space (span of columns)
col_space = A

# Null space
N = null_space(A)

# Row space = span of rows
row_space = A.T

# Left null space = null space of A^T
left_null = null_space(A.T)

print("Matrix A:\n", A)
print("Null space basis:\n", N)
print("Left null space basis:\n", left_null)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Null space basis:
 [[-0.40824829]
 [ 0.81649658]
 [-0.40824829]]
Left null space basis:
 [[ 0.40824829]
 [-0.81649658]
 [ 0.40824829]]


In [28]:
# Property of rank

# Create matrix
B = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

# Compute ranks
rank_A = matrix_rank(A)
rank_B = matrix_rank(B)
rank_AplusB = matrix_rank(A+B)

print("rank(A) =", rank_A)
print("rank(B) =", rank_B)
print("rank(A+B) =", rank_AplusB)

rank(A) = 2
rank(B) = 1
rank(A+B) = 2


In [29]:
# Check inequality
print("Check: rank(A+B) ≤ rank(A) + rank(B) ?")
print(f"{rank_AplusB} ≤ {rank_A + rank_B}")

Check: rank(A+B) ≤ rank(A) + rank(B) ?
2 ≤ 3
